# Generated by Django 4.1.1 on 2022-10-06 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_friendrequest_fiendlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FiendList',
            new_name='FriendList',
        ),
    ]
